# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [25]:
import numpy as np

In [26]:
my_array = np.arange(10)
print(my_array)
print(my_array[-1::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [27]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [28]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [79]:
my_matrix = np.arange(1,21)
my_matrix = my_matrix.reshape((4,5))
print(my_matrix)
np.flip(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [80]:
my_matrix[0:2,0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [85]:
my_matrix = np.arange(1,21)
my_matrix = my_matrix.reshape((4,5))
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [165]:
my_matrix[0:4:2, 0::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [170]:
my_matrix[0:3, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [164]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
n = []
for i in x:
    if i == "Loro":
        n.append(i)
        y = np.array(n)

print(y)

['Loro' 'Loro']


In [160]:
new = np.array(z for z in list(x) if z == "Loro")
print(new)

<generator object <genexpr> at 0x0000024654FC2DC8>


In [93]:
filtered = x[x == "Loro"]
filtered

array(['Loro', 'Loro'], dtype='<U5')

In [ ]:
m = [row for row in l if 'a' == "Loro"]

In [94]:
filter(lambda i: i == "Loro" i )

SyntaxError: invalid syntax (<ipython-input-94-d1582446a5a1>, line 1)

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [49]:
my_matrix9 = np.arange(1,21)
my_matrix9 = my_matrix9.reshape((2,5,2))
print(my_matrix9)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [52]:
my_matrix = np.arange(1,21)
my_matrix = my_matrix.reshape((4,5))
matrix10 = np.flip(my_matrix)
print(matrix10)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [61]:
import sys
ceros = np.zeros(10)
print(sys.getsizeof(ceros))

184


In [62]:
print(ceros.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [57]:

ceros[3] = 1
print(ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [65]:
vector = np.arange(10,50)
print(vector)
np.flip(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [72]:
l = [1,2,0,0,4,0]
x = []
np.array(l)
np.array(x)
for i, elem in enumerate(l):
    if elem != 0:
        x.append(i)

print(x)

[0, 1, 4]


In [75]:
nocero = np.nonzero(l)
print(nocero)

(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [77]:
x =np.random.randint( 100, size = (10,10))
print(x)
print(np.min(x))
print(np.max(x))

[[52 12 95  0 75  8 22 62 20 18]
 [42  1 73 43 36 26 45 78 67  7]
 [19 60 62 10 19 98 25  2 85 38]
 [64 54 53 23 26 99 44 50 50 84]
 [15 33 11 92 50 24 45 83 10 70]
 [17 58 11 91 84 39 29 29 64 55]
 [97 57 44 56 89 94 54 46 48 89]
 [12 44 17 83 61 65 47 43 31 10]
 [61 43 25 72 53 17 47 70 91 70]
 [34  9  1 23 97 22 16 31  7 79]]
0
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [78]:
treinta = np.arange(30)
treinta.mean()

14.5

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [99]:
ones = np.ones(9).reshape((3,3))
ones[1,1] = 0
ones

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [146]:
ceros = np.zeros((8,8), dtype=int)
ceros[1::2,::2] = 1
ceros[::2,1::2] = 1
print(ceros)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [154]:
a = np.array([[0, 1],[1,0]])
print(np.tile(a, (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [153]:
a


array([[0, 1],
       [1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [111]:
x =np.random.randint(20, size = (5,5))
y = (x - np.mean(x))/np.std(x)
y

array([[ 1.62641795, -0.06776741, -0.27954059, -1.55017961, -1.12663327],
       [-0.70308693,  0.99109844,  0.5675521 ,  0.5675521 ,  0.77932527],
       [ 0.77932527, -1.55017961,  1.62641795,  0.14400576,  0.5675521 ],
       [ 0.5675521 , -0.70308693,  1.41464478, -1.12663327,  0.35577893],
       [-0.49131376, -1.97372595,  0.35577893, -1.12663327,  0.35577893]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [124]:
arr = np.arange(11)
print(arr)
arr2 = arr
arr2[3:9] = -1
print(arr2)
arr3 = np.where(arr2 < 0, None , arr2)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[0 1 2 None None None None None None 9 10]


In [125]:
arr = np.arange(11)
arr3 = arr
arr3[3:9] = -arr3[3:9]
arr3

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [131]:

arr = np.arange(11)
arr[3:9] =  -arr[3:9]
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.