# 02 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). Assign it to a variable called chipo.

This time we are going to pull data directly from the internet.

In [3]:
address = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

In [4]:
chipo = pd.read_csv(address,sep='\t')
chipo

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

### Step 3. Name of the most expensive products (item_name)

¿Recuerdas el `map`? En **pandas** tienes el método [`apply`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html) y en para resolver este ejercicio te puede ser muy útil. 

Pero no acaba ahí https://stackoverflow.com/questions/19798153/difference-between-map-applymap-and-apply-methods-in-pandas

In [5]:
simple = lambda x: x.replace("$","")
chipo['item_price'] = chipo['item_price'].map(simple)
chipo['item_price'] = chipo['item_price'].map(lambda x: float(x))

In [8]:
'''
chipo['item_price']= chipo.map(lambda x: float(x))
'''
chipo

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]        3.39  
2                                               [Apple]        3.39  
3                                                   NaN        2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
...                                                 ...         ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75  

[4622 rows x 5 columns]

In [7]:
chipo['item_price'].str[1:].astype(float)

AttributeError: Can only use .str accessor with string values!

In [162]:
chipo.item_price.apply(lambda x: float(x[1:]))

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...  
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [168]:
chipo = chipo.item_price.apply(lambda x: float(x[1:]))

In [170]:
chipo["item_price"] = chipo.item_price.apply(lambda x: float(x[1:]))

AttributeError: 'Series' object has no attribute 'item_price'

In [169]:
chipo.sort_values("item_price", ascending=False)

ValueError: No axis named item_price for object type Series

### Step 4. How many products cost more than $10.00?

In [9]:
chipo[chipo['item_price'] > 10.00]

order_id  quantity           item_name  \
4            2         2        Chicken Bowl   
5            3         1        Chicken Bowl   
7            4         1       Steak Burrito   
13           7         1        Chicken Bowl   
23          12         1     Chicken Burrito   
...        ...       ...                 ...   
4610      1830         1       Steak Burrito   
4611      1830         1      Veggie Burrito   
4617      1833         1       Steak Burrito   
4618      1833         1       Steak Burrito   
4619      1834         1  Chicken Salad Bowl   

                                     choice_description  item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
7     [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25  
23    [[Tomatillo-Green Chili Salsa (Medium), Tomati...       10.98  
...                                                 ...         ...  
4610  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4611  [Tomatillo Green Chili Salsa, [Rice, Fajita Ve...       11.25  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  

[1130 rows x 5 columns]

In [ ]:
##Llegados a este punto es que ya no se qué hacer

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [30]:
prices = chipo[["item_name","item_price"]]
prices

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
...                                     ...        ...
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [31]:
prices.sort_values(["item_name"])

item_name item_price
3389  6 Pack Soft Drink    $12.98 
341   6 Pack Soft Drink     $6.49 
1849  6 Pack Soft Drink     $6.49 
1860  6 Pack Soft Drink     $6.49 
2713  6 Pack Soft Drink     $6.49 
...                 ...        ...
2384  Veggie Soft Tacos     $8.75 
781   Veggie Soft Tacos     $8.75 
2851  Veggie Soft Tacos     $8.49 
1699  Veggie Soft Tacos    $11.25 
1395  Veggie Soft Tacos     $8.49 

[4622 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [106]:
chipo.sort_values("item_price", ascending=False)

ValueError: No axis named item_price for object type Series

V2

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [40]:
chipo['item_name'] = chipo.groupby('Veggie Salad Bow')['Veggie Salad Bow'].transform('item_name')

KeyError: 'Veggie Salad Bow'

In [167]:
chipo.groupby["quantity"]('Veggie Salad Bow').transform('item_name')

TypeError: 'method' object is not subscriptable

In [12]:
chipo["item_name"].value_counts()

Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Cr

In [20]:
chipo["item_name"].value_counts().values[chipo["item_name"].value_counts().index == "Veggie Salad"]

#chipo["item_name"].value_counts().values hace de serie sobre la que se da el valor siguiente para pasarla con encima con los true

array([6], dtype=int64)

In [17]:

arr1= np.array([3,4,5])
arr1[[True,True,False]]

array([3, 4])

### Step 9. How many times did someone order more than one Canned Soda?

In [24]:
chipo

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]        3.39  
2                                               [Apple]        3.39  
3                                                   NaN        2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
...                                                 ...         ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75  

[4622 rows x 5 columns]

In [27]:
chipo["quantity"].value_counts().values

array([4355,  224,   28,   10,    1,    1,    1,    1,    1], dtype=int64)

In [32]:
chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)].shape[0]

20

In [33]:
df_canned = chipo[chipo.item_name == "Canned Soda"]
df_canned

order_id  quantity    item_name choice_description  item_price
18           9         2  Canned Soda           [Sprite]        2.18
28          14         1  Canned Soda       [Dr. Pepper]        1.09
51          23         2  Canned Soda     [Mountain Dew]        2.18
53          24         1  Canned Soda           [Sprite]        1.09
107         47         1  Canned Soda       [Dr. Pepper]        1.09
...        ...       ...          ...                ...         ...
3897      1562         1  Canned Soda     [Mountain Dew]        1.09
3926      1575         1  Canned Soda       [Dr. Pepper]        1.09
3936      1578         1  Canned Soda  [Diet Dr. Pepper]        1.09
4008      1604         1  Canned Soda        [Diet Coke]        1.09
4051      1621         1  Canned Soda           [Sprite]        1.09

[104 rows x 5 columns]

In [25]:
chipo["quantity"].value_counts().values[chipo["quantity"].value_counts().index == "Canned Soda" > 1]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()